# Generated by Django 5.0.6 on 2024-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('cast', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('extract', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('thumbnail_width', models.IntegerField(default=0)),
                ('thumbnail_height', models.IntegerField(default=0)),
            ],
        ),
    ]
