# Generated by Django 5.0.6 on 2024-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('genres', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('runtime', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('premiered', models.DateField()),
                ('ended', models.DateField()),
                ('official_site', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('imdb_id', models.CharField(max_length=20)),
                ('image_medium', models.URLField(blank=True, null=True)),
                ('image_original', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
