# Generated by Django 5.0.6 on 2024-05-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tvshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='premiered',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
