# Generated by Django 5.0.6 on 2024-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tvshow_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='imdb_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
